# Generated by Django 2.2.16 on 2022-11-03 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.ManyToManyField(
                related_name='following',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Авторы',
            ),
        ),
    ]
